# Generated by Django 5.0.4 on 2026-03-07 03:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('notification_type', models.CharField(choices=[('NEW_MEMBER_CREATED', 'New Member Created'), ('PROFILE_PENDING_APPROVAL', 'Profile Pending Approval'), ('MEMBER_APPROVED', 'Member Approved'), ('MEMBER_MERGED', 'Member Merged'), ('MEDICAL_RECORD_CREATED', 'Medical Record Created'), ('CELL_GROUP_NEW_MEMBER', 'Cell Group New Member'), ('FOLLOWUP_ASSIGNED', 'Follow-Up Assigned'), ('FOLLOWUP_COMPLETED', 'Follow-Up Completed'), ('WORKER_CREATED', 'Worker Created'), ('CELL_GROUP_DISBANDED', 'Cell Group Disbanded'), ('GENERAL', 'General')], default='GENERAL', max_length=50)),
                ('entity_type', models.CharField(blank=True, max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=100)),
                ('action_url', models.TextField(blank=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
