# Generated by Django 5.0.4 on 2026-03-07 03:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('NEW_MEMBER', 'New Member'), ('PENDING_APPROVAL', 'Pending Approval'), ('MEMBER', 'Member'), ('WORKER', 'Worker'), ('INACTIVE', 'Inactive')], db_index=True, default='NEW_MEMBER', max_length=30)),
                ('source', models.CharField(blank=True, choices=[('MEDICAL', 'Medical'), ('FOLLOWUP', 'Follow Up'), ('CELL', 'Cell Group'), ('ADMIN', 'Admin')], max_length=30)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'persons',
            },
        ),
    ]
