# Generated by Django 5.0.4 on 2026-03-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_systemuser_department_systemuser_must_reset_password'),
    ]

    def migrate_dept_roles(apps, schema_editor):
        SystemUser = apps.get_model('accounts', 'SystemUser')
        SystemUser.objects.filter(role='DEPT_LEADER').update(role='HOD')
        SystemUser.objects.filter(role='DEPT_ASST').update(role='ASST_HOD')

    operations = [
        # Run data migration BEFORE altering the field constraints
        migrations.RunPython(migrate_dept_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='systemuser',
            name='role',
            field=models.CharField(
                choices=[
                    ('ADMIN',      'Admin'),
                    ('MEDICAL',    'Medical Team'),
                    ('FOLLOWUP',   'Follow Up Team'),
                    ('CELL_ADMIN', 'Cell Admin'),
                    ('HOD',        'Head of Department'),
                    ('ASST_HOD',   'Assistant Head of Department'),
                    ('WELFARE',    'Welfare Officer'),
                    ('PRO',        'Public Relations Officer'),
                    ('HR',         'HR Team'),
                ],
                db_index=True, default='FOLLOWUP', max_length=30,
            ),
        ),
    ]
