# Generated by Django 5.0.4 on 2026-03-07 03:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0002_alter_person_options_person_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CellGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('purpose', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DISBANDED', 'Disbanded')], db_index=True, default='ACTIVE', max_length=20)),
                ('disbanded_at', models.DateTimeField(blank=True, null=True)),
                ('disbanded_reason', models.TextField(blank=True)),
                ('meeting_schedule', models.CharField(blank=True, max_length=255)),
                ('meeting_location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_groups_administered', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_groups_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cell_groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CellGroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('LEADER', 'Leader'), ('ASSISTANT', 'Assistant')], default='MEMBER', max_length=30)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('left_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_via', models.CharField(blank=True, choices=[('PHONE_SEARCH', 'Phone Search'), ('MANUAL', 'Manual'), ('ADMIN', 'Admin')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_members_added', to=settings.AUTH_USER_MODEL)),
                ('cell_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cellgroups.cellgroup')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cellgroup_memberships', to='persons.person')),
            ],
            options={
                'db_table': 'cell_group_members',
                'unique_together': {('cell_group', 'person')},
            },
        ),
    ]
